### ISSUE TITLE
fix citation styles

### ISSUE THREAD

**Issue by clinssen** [med-ayssar/Master_report#34]
Please review and fix minor typography on the citations (like {NEST} instead of NEST, so it doesn't render in lower case), and for websites, add the date and time at which it was retrieved.

**Comment by med-ayssar** [comment]
Can you give me an example, because sometimes I overlook these things?

**Comment by clinssen** [comment]
If you write ``title="NEST"`` in the .bib file, it gets rendered as "nest". Use ``title="{NEST}" to render it as "NEST". Similar for NESTML.
